### PR TITLE
Added STEP for ForecastingPipeline

### PR DESCRIPTION
**Pull request by aiwalter**
Added STEP for ForecastingPipeline
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

### CODE REVIEW

**Comment by aiwalter** [comment]
@fkiraly just pinging you, maybe you can provide feedback?
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by mloning** [comment]
@aiwalter @fkiraly we should set up another call to sketch out the design, similar to the call on forecasting model evaluation. I post something on Slack.

**Comment by fkiraly** [comment]
Yes, also see:
https://github.com/alan-turing-institute/sktime/issues/798
https://github.com/alan-turing-institute/sktime/issues/763

(instances of discussions on pipelines I'm aware of)

**Comment by aiwalter** [comment]
@mloning just added the stuff from the call and cleaned it a bit
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Review by mloning — APPROVED** [review]
Let's merge these as initial notes. 
Any comments before we merge?

**Pull request merged**
