### PR TITLE
Benchmarking

### PR DESCRIPTION
**Pull request by ViktorKaz**
Initial proposal for enhancement of the benchmarking module of sktime

### CODE REVIEW

**Comment by mloning** [comment]
Thanks @ViktorKaz - will take a look!

**Comment by mloning** [comment]
One general consideration is whether to move this outside of the base package and set up a separate benchmarking module under the sktime organisation on GitHub. 

I'm happy to merge this quickly and then iterate over different discussion points.

**Comment by mloning** [comment]
Hi @ViktorKaz, is this still being worked on or shall we merge it as an initial draft?

**Comment by ViktorKaz** [comment]
Hi @mloning, you can merge it as an initial draft, I will open a new PR when I continue working on it.

**Comment by mloning** [comment]
@ViktorKaz could you update the number of from 8 to 9? There's already a step 8 now.

**Comment by ViktorKaz** [comment]
@mloning ok, done

**Pull request merged**
