### PR TITLE
STEP: flag manager and config interface

### PR DESCRIPTION
**Pull request by fkiraly**
This STEP introduces an abstract flag manager and a config interface, which parallels the tag interface.

An implementation is available in https://github.com/sktime/sktime/pull/3822

### CODE REVIEW

**Comment by fkiraly** [comment]
FYI @RNKuhns

**Comment by RNKuhns** [comment]
> FYI @RNKuhns 

@fkiraly I will take a look.

**Review by RNKuhns — CHANGES_REQUESTED** [review]
@fkiraly I will send along a few minor suggested text tweaks. But I agree with this in theory.

However, 2 items I'd like to see addressed are: 

- Why not just add the flag manager logic to BaseObject directly, instead of having it inherit from the flag manager? Are there uses other than through BaseObject that I'm not considering (hence the mixing is useful to have around)?
- global config system (through singleton like we talked about a while back). I think for the config part a user should be able to it locally (on estimator/base object) or globally (indicate not to do input checks globallly). I'm thinking base config for should be looked up from this global config, unless overridden. I can provide some text and examples on that if it is helpful.

**Comment by fkiraly** [comment]
> Why not just add the flag manager logic to BaseObject directly, instead of having it inherit from the flag manager?

That would be an option I wouldn't be opposed to, I just thought:

* that would increase the number of methods in `BaseObject` even more - "an object/function should do one thing and only one thing" and so on. Arguably that depends on the definition of what thing `BaseObject` is, of course, but I find the "flag management" concern it's better localized this way.
* I can also imagine a case where one may like to manage tags/flags in an object that is not `BaseObject descendant, although this is more of a hypothetical right now

> I'm thinking base config for should be looked up from this global config, unless overridden. I can provide some text and examples on that if it is helpful.

Yes, that would be helpful!

I haven't figured out how to avoid coupling the `BaseObject` to the global config. One idea would be an attribute that the flag manager mixin looks up, and you can hard code it in the consumer package `BaseObject`, which inherits from `skbase.BaseObject`, but that seems a little clunky.

Another question I have, should we merge this in `sktime` 0.16.0, so we can build input/output check control on it, or should we wait?

**Comment by fkiraly** [comment]
(added discussion of alt design)

**Pull request merged**
