### PR TITLE
STEP for pyWATTS enhancement

### PR DESCRIPTION
**Pull request by benHeid**
#### What does this implement/fix? Explain your changes.
This STEP proposes to cooperate with pyWATTS to enable a graph pipeline in sktime.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
I think this is a great start!
This is definitely more than sufficient for discussion next weeks.
Kindly let me know where you would like to have input.

Some points that I see here:

* most importantly, there is a bit of a discrepancy between more pywatts-sided usage designs and the `sktime` architecture. For instance, `sktime` estimators have different core API methods, such as `fit`/`transform` (transformer) and `fit`/`predict` (forecasters, classifiers), not `train`. How the two map onto each other might be worth discussing.
* maybe it would be a good idea to paste the open design questions we identified from the mardown somewhere in here, e.g., at the end?
* requirements refer only to transformers. Are we restricting ourselves only to transformers at the moment? I think where it becomes "really interesting" is once estimators of specific type, e.g., forecasters, are involved.

**Comment by fkiraly** [comment]
Question FK - what is the difference between solution 1 and 3?

**Comment by fkiraly** [comment]
question: in solution 3, is the `Transformer` one single class that is always used, or would it be a specific (concrete) sktime transformer?

**Comment by fkiraly** [comment]
question: in solution 3/4, you write `train`, I assume if we use the `sktime` transformer interface, this would be `fit` or `fit_transform`?

**Comment by fkiraly** [comment]
looks like current pywatts design, square bracket dunder is like a `ColumnSelectionTransformer`

**Comment by benHeid** [comment]
> * designs and the `sktime` architecture. For instance, `sktime` estimators have different core API methods, such as `fit`/`transform` (transformer) and `fit`/`predict` (forecasters, classifiers), not `train`. How the two map onto each other might be worth discussing.

Solution 1 is the current pyWATTS solution. I.e., the pipeline has to be initialised before the structure of the pipeline is specified. Here, the column selection is done by the square brackets dunder. Solution three is a full keras API. Where the pipeline is initialisied with the inputs and the outputs after the structure is defined. This solution would use an other mechanism for selecting the input columns. Here I proposed something like `Column("bar")` which is in some way analogue to the InputLayer of Keras

**Comment by fkiraly** [comment]
solution 4 looks like it has a typo - `step_information` should all be `graph_pipeline`

**Pull request closed without merging**
